apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: vote-app-application
  namespace: acm
  labels:
    app: vote-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: vote-app
